# Generated by Django 3.1.13 on 2021-11-19 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0005_auto_20211116_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('uid', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=6, max_length=6, prefix='', primary_key=True, serialize=False, verbose_name='Unique identifier')),
                ('email', models.EmailField(default=None, max_length=254, verbose_name='Email')),
                ('invite_time', models.DateTimeField(auto_now_add=True, verbose_name='Invite time')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='organizations.organization', verbose_name='Organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to=settings.AUTH_USER_MODEL, verbose_name='User inviting')),
            ],
            options={
                'verbose_name': 'Invitation',
                'verbose_name_plural': 'Invitations',
                'ordering': ['invite_time'],
                'permissions': [],
                'default_permissions': [],
                'unique_together': {('organization', 'email')},
            },
        ),
    ]
