# Generated by Django 3.1.13 on 2021-12-15 22:38

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0005_auto_20211116_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField(default=True, help_text='Whether the board is available to all oraganization members.', verbose_name='Public')),
                ('title', models.CharField(db_index=True, default=None, help_text='Board title is immutable to prevent URL changes.', max_length=50, verbose_name='Title')),
                ('description', models.TextField(blank=True, default=None, verbose_name='Description')),
                ('slug', models.SlugField(default=None, error_messages={'null': 'Slug can not be null.'}, help_text='Slug will be generated based on title and random number.', unique=True, verbose_name='Slug')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='organizations.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Board',
                'verbose_name_plural': 'Boards',
                'ordering': ['title'],
                'permissions': [],
                'get_latest_by': 'modified',
                'default_permissions': ['view'],
            },
        ),
    ]
