# Generated by Django 3.1.13 on 2021-12-23 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'default_permissions': ['view'], 'get_latest_by': 'modified', 'ordering': ['title'], 'permissions': [('add_list', 'Can create new list in the board'), ('add_card', 'Can create new card in the board')], 'verbose_name': 'Board', 'verbose_name_plural': 'Boards'},
        ),
        migrations.AlterField(
            model_name='board',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='board',
            name='public',
            field=models.BooleanField(default=True, help_text='Whether the board is available to all members or only selected.', verbose_name='Public'),
        ),
    ]
