# Generated by Django 3.1.13 on 2021-11-05 17:57

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('public', models.BooleanField(default=True, verbose_name='Is public')),
                ('website', models.URLField(blank=True, unique=True, verbose_name='Website URL')),
                ('location', django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='Location country')),
                ('verified', models.BooleanField(default=False, verbose_name='Is verified')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['name'],
            },
        ),
    ]
