# Generated by Django 3.1.13 on 2021-11-07 10:26

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='location',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Location country'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='website',
            field=models.URLField(blank=True, null=True, unique=True, verbose_name='Website URL'),
        ),
    ]
