# Generated by Django 3.1.13 on 2021-11-11 19:23

from django.apps.registry import Apps
from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def create_groups(apps: Apps, schema_editor: BaseDatabaseSchemaEditor):
    """
    Create permission groups for application-wide usage.
    """
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    organization_representatives_group, created = Group.objects.get_or_create(
        name="Organization Representatives"
    )

    # Add group permissions (if not already added)
    can_add_organization = Permission.objects.get(codename="add_organization")
    organization_representatives_group.permissions.add(can_add_organization)


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_auto_20211107_1326"),
    ]

    operations = [migrations.RunPython(create_groups)]
