# Generated by Django 3.1.13 on 2021-11-13 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0003_auto_20211111_2223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'default_permissions': ['add', 'change', 'delete', 'view'], 'get_latest_by': 'id', 'ordering': ['name'], 'permissions': [], 'verbose_name': 'Organization', 'verbose_name_plural': 'Organizations'},
        ),
        migrations.AddField(
            model_name='organization',
            name='representative',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='users.user', verbose_name='Representative'),
            preserve_default=False,
        ),
    ]
