# Generated by Django 3.1.13 on 2021-11-16 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0004_auto_20211113_1246"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organization",
            options={
                "default_permissions": ["add", "change", "delete", "view"],
                "get_latest_by": "id",
                "ordering": ["name"],
                "permissions": [
                    ("view_member", "Can view member(s) of organization"),
                    ("invite_member", "Can invite (add) new member(s) to organization"),
                    ("kick_member", "Can kick (delete) member(s) from organization"),
                ],
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
            },
        ),
    ]
